//------------------------------------------------------------------------------
// <auto-generated>
//		This code was generated from a template.
//
//		Manual changes to this file may cause unexpected behavior in your application.
//		Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Objects;

namespace System.Data.Objects
{
	/// <summary>
	///	Service base class which provides Execute methods for accessing the Object Context.
	/// </summary>
	public abstract partial class ServiceBase<TContext>
		where TContext : ObjectContext, new()
	{
		#region Excute
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		protected TReturn ExecuteReturn<TReturn>(Func<TContext, TReturn> action)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		protected void Execute(Action<TContext> action)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1>(Func<TContext, TArg1, TReturn> action, TArg1 arg1)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		protected void Execute<TArg1>(Action<TContext, TArg1> action, TArg1 arg1)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2>(Func<TContext, TArg1, TArg2, TReturn> action, TArg1 arg1, TArg2 arg2)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		protected void Execute<TArg1, TArg2>(Action<TContext, TArg1, TArg2> action, TArg1 arg1, TArg2 arg2)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3>(Func<TContext, TArg1, TArg2, TArg3, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3>(Action<TContext, TArg1, TArg2, TArg3> action, TArg1 arg1, TArg2 arg2, TArg3 arg3)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4>(Action<TContext, TArg1, TArg2, TArg3, TArg4> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		/// <typeparam name="TArg11">The type of the Eleventh argument of the method.</typeparam>
		/// <param name="arg11">The value of the Eleventh argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		/// <typeparam name="TArg11">The type of the Eleventh argument of the method.</typeparam>
		/// <param name="arg11">The value of the Eleventh argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		/// <typeparam name="TArg11">The type of the Eleventh argument of the method.</typeparam>
		/// <param name="arg11">The value of the Eleventh argument of the method.</param>
		/// <typeparam name="TArg12">The type of the Twelfth argument of the method.</typeparam>
		/// <param name="arg12">The value of the Twelfth argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		/// <typeparam name="TArg11">The type of the Eleventh argument of the method.</typeparam>
		/// <param name="arg11">The value of the Eleventh argument of the method.</param>
		/// <typeparam name="TArg12">The type of the Twelfth argument of the method.</typeparam>
		/// <param name="arg12">The value of the Twelfth argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		/// <typeparam name="TArg11">The type of the Eleventh argument of the method.</typeparam>
		/// <param name="arg11">The value of the Eleventh argument of the method.</param>
		/// <typeparam name="TArg12">The type of the Twelfth argument of the method.</typeparam>
		/// <param name="arg12">The value of the Twelfth argument of the method.</param>
		/// <typeparam name="TArg13">The type of the Thirteenth argument of the method.</typeparam>
		/// <param name="arg13">The value of the Thirteenth argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		/// <typeparam name="TArg11">The type of the Eleventh argument of the method.</typeparam>
		/// <param name="arg11">The value of the Eleventh argument of the method.</param>
		/// <typeparam name="TArg12">The type of the Twelfth argument of the method.</typeparam>
		/// <param name="arg12">The value of the Twelfth argument of the method.</param>
		/// <typeparam name="TArg13">The type of the Thirteenth argument of the method.</typeparam>
		/// <param name="arg13">The value of the Thirteenth argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		/// <typeparam name="TArg11">The type of the Eleventh argument of the method.</typeparam>
		/// <param name="arg11">The value of the Eleventh argument of the method.</param>
		/// <typeparam name="TArg12">The type of the Twelfth argument of the method.</typeparam>
		/// <param name="arg12">The value of the Twelfth argument of the method.</param>
		/// <typeparam name="TArg13">The type of the Thirteenth argument of the method.</typeparam>
		/// <param name="arg13">The value of the Thirteenth argument of the method.</param>
		/// <typeparam name="TArg14">The type of the Fourteenth argument of the method.</typeparam>
		/// <param name="arg14">The value of the Fourteenth argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13, TArg14 arg14)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		/// <typeparam name="TArg11">The type of the Eleventh argument of the method.</typeparam>
		/// <param name="arg11">The value of the Eleventh argument of the method.</param>
		/// <typeparam name="TArg12">The type of the Twelfth argument of the method.</typeparam>
		/// <param name="arg12">The value of the Twelfth argument of the method.</param>
		/// <typeparam name="TArg13">The type of the Thirteenth argument of the method.</typeparam>
		/// <param name="arg13">The value of the Thirteenth argument of the method.</param>
		/// <typeparam name="TArg14">The type of the Fourteenth argument of the method.</typeparam>
		/// <param name="arg14">The value of the Fourteenth argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13, TArg14 arg14)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
				}
			}
		}
		/// <summary>
		/// Executes an action against the context object and returns the return value of the action.
		/// </summary>
		/// <typeparam name="TReturn">The type of object returned from the action.</typeparam>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		/// <typeparam name="TArg11">The type of the Eleventh argument of the method.</typeparam>
		/// <param name="arg11">The value of the Eleventh argument of the method.</param>
		/// <typeparam name="TArg12">The type of the Twelfth argument of the method.</typeparam>
		/// <param name="arg12">The value of the Twelfth argument of the method.</param>
		/// <typeparam name="TArg13">The type of the Thirteenth argument of the method.</typeparam>
		/// <param name="arg13">The value of the Thirteenth argument of the method.</param>
		/// <typeparam name="TArg14">The type of the Fourteenth argument of the method.</typeparam>
		/// <param name="arg14">The value of the Fourteenth argument of the method.</param>
		/// <typeparam name="TArg15">The type of the Fifteenth argument of the method.</typeparam>
		/// <param name="arg15">The value of the Fifteenth argument of the method.</param>
		protected TReturn ExecuteReturn<TReturn, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15>(Func<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TReturn> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13, TArg14 arg14, TArg15 arg15)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					return action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
				}
			}
		}

		/// <summary>
		/// Executes an action against the context object.
		/// </summary>
		/// <param name="action">The action to be executed</param>
		/// <typeparam name="TArg1">The type of the First argument of the method.</typeparam>
		/// <param name="arg1">The value of the First argument of the method.</param>
		/// <typeparam name="TArg2">The type of the Second argument of the method.</typeparam>
		/// <param name="arg2">The value of the Second argument of the method.</param>
		/// <typeparam name="TArg3">The type of the Third argument of the method.</typeparam>
		/// <param name="arg3">The value of the Third argument of the method.</param>
		/// <typeparam name="TArg4">The type of the Fourth argument of the method.</typeparam>
		/// <param name="arg4">The value of the Fourth argument of the method.</param>
		/// <typeparam name="TArg5">The type of the Fifth argument of the method.</typeparam>
		/// <param name="arg5">The value of the Fifth argument of the method.</param>
		/// <typeparam name="TArg6">The type of the Sixth argument of the method.</typeparam>
		/// <param name="arg6">The value of the Sixth argument of the method.</param>
		/// <typeparam name="TArg7">The type of the Seventh argument of the method.</typeparam>
		/// <param name="arg7">The value of the Seventh argument of the method.</param>
		/// <typeparam name="TArg8">The type of the Eighth argument of the method.</typeparam>
		/// <param name="arg8">The value of the Eighth argument of the method.</param>
		/// <typeparam name="TArg9">The type of the Ninth argument of the method.</typeparam>
		/// <param name="arg9">The value of the Ninth argument of the method.</param>
		/// <typeparam name="TArg10">The type of the Tenth argument of the method.</typeparam>
		/// <param name="arg10">The value of the Tenth argument of the method.</param>
		/// <typeparam name="TArg11">The type of the Eleventh argument of the method.</typeparam>
		/// <param name="arg11">The value of the Eleventh argument of the method.</param>
		/// <typeparam name="TArg12">The type of the Twelfth argument of the method.</typeparam>
		/// <param name="arg12">The value of the Twelfth argument of the method.</param>
		/// <typeparam name="TArg13">The type of the Thirteenth argument of the method.</typeparam>
		/// <param name="arg13">The value of the Thirteenth argument of the method.</param>
		/// <typeparam name="TArg14">The type of the Fourteenth argument of the method.</typeparam>
		/// <param name="arg14">The value of the Fourteenth argument of the method.</param>
		/// <typeparam name="TArg15">The type of the Fifteenth argument of the method.</typeparam>
		/// <param name="arg15">The value of the Fifteenth argument of the method.</param>
		protected void Execute<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15>(Action<TContext, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13, TArg14 arg14, TArg15 arg15)
		{
			if (action == null) throw new ArgumentNullException("action");

			try
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
				}
			}
			catch(EntityCommandExecutionException)
			{
				using (TContext context = new TContext())
				{
					action(context, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
				}
			}
		}
		#endregion
	}
}
