using System.Security.Principal;

namespace System.Security
{
	/// <summary>
	/// Defines a class which provides Tokens
	/// </summary>
  public interface ITokenProvider
  {
		/// <summary>
		/// Generates a token from the supplied components.
		/// </summary>
		/// <param name="components">The components which will be used to generate the Token</param>
		/// <returns>Returns a Base64 string containing the bytes generated by the Keyed Hash Algorithm</returns>
		string GetToken(params object[] components);
  }
}
